### PR TITLE
Make manual_file a non-mandatory setting

### PR DESCRIPTION
**Pull request by brucellino**
Ref #17

### CODE REVIEW

**Comment by gwarf** [comment]
Would it be better to check that manual_file is set when manual is true?

**Comment by brucellino** [comment]
The logic should definitely be : 

```
if you are doing manual configuration
  try check manual file option
  throw exception
```

However, by putting it in the parameter list, it becomes mandatory. So we need a special block of logic for `manual_file` conditional on `manual == True`

I think this is the "right" way to fix it. Let me send through a suggestion.

**Comment by brucellino** [comment]
Now would be a real good time to have some specs for testing this script :smiley:

**Comment by brucellino** [comment]
ok, I'm happy for review to start.

**Comment by brucellino** [comment]
@gwarf you happy?
@pandreetto , @EGI-Foundation/bdii ?

**Pull request merged**
